version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Flask-App

hooks:
  BeforeInstall:
    - location: setup.sh
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      runas: ec2-user
  ApplicationStop:
    - location: application_stop.sh
      runas: ec2-user
      
