version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Flask-App
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
