name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code (needed for docker build context)
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (for advanced build support)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 3: Login to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build & Push Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest

    # Step 5: SSH into EC2 and deploy
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu

          # Clone the repo if not already present
          if [ ! -d "FlaskApp" ]; then
            git clone https://github.com/your-username/FlaskApp.git
          fi

          cd FlaskApp

          # Pull latest changes
          git pull origin main

          # Run deployment scripts
          bash stop_application.sh || true
          bash start_application.sh
