    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu

          # Clone the repo if it doesn't already exist
          if [ ! -d "FlaskApp" ]; then
            git clone https://github.com/your-username/FlaskApp.git
          fi

          cd FlaskApp

          # Pull the latest code
          git pull origin main

          # Run deployment scripts
          bash stop_application.sh || true
          bash start_application.sh
