name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: varuntej18
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t varuntej18/githubactionsdemo:latest .
        docker push varuntej18/githubactionsdemo:latest

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu
          if [ ! -d "FlaskApp" ]; then
            git clone https://github.com/VTS072Varun/FlaskApp.git
          fi
          cd FlaskApp
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          bash stop_application.sh || true
          bash start_application.sh
